### ISSUE TITLE
Index is added as field an array is in the query

### ISSUE THREAD

**Issue by bret-hubbard** [dupski/json-to-graphql-query#16]
When an array is passed in the current functionality is to add the index of the array as a field on the query. I know that arrays aren't supported currently but with the includeFalsyKeys PR (see #15)  this becomes more of an issue.

My first thought (and the easiest to implement) would be to just grab the keys off the first object in the array. Alternatively we could get all of the keys from all of the objects in the array.

Again, I am happy to submit a PR if you are interested in this functionality.

Thanks!

**Comment by dupski** [comment]
Hmm, my feeling on this one is we should probably just drop arrays? (just keep the key that references them)

JS arrays can contain any primitives including numbers and null which are not valid GraphQL nodes

**Comment by dupski** [comment]
We've decided to search the array for the first object and use the keys from that. Released as `v1.9.0`
