### ISSUE TITLE
Use EnumType in Object-Parameter

### ISSUE THREAD

**Issue by mertins-codamic** [dupski/json-to-graphql-query#22]
Hey @dupski,
thank you for this lib. It's exactly what i was looking for. But now i'm stuck by passing EnumTypes in Objects as Parameter.

```
const query = {
  mutation: {
    create: {
      __aliasFor: 'createPost',
      __args: {
        initial: {title: "XYZ" , status: new EnumType("OPEN")},
      },
      id: true,
    },
  },
};
```

results in:
`mutation { create: createPost (initial: {title: "XYZ", status: {value: "OPEN"}}) { id }}`

expected:
`mutation { create: createPost (initial: {title: "XYZ", status: OPEN}) { id }}`

Can you help here? Thanks :)

**Comment by mertins-codamic** [comment]
Additional Info: I figure out why this happens.
I used EnumType from other package. (Core-Lib imports json-to-graphql-query and project itself import EnumType, so "instanceof" does not match.
Fix it by using:
`export {EnumType as EnumType} from 'json-to-graphql-query';`
in my index.js in Core-Lib.

**Comment by dupski** [comment]
Glad you sorted it @mertins-codamic  :)

**Comment by tdelabro** [comment]
@dupski I'm having this exact behaviour.

I'm importing `import { EnumType } from 'json-to-graphql-query';`
in one file, and `import { jsonToGraphQLQuery } from 'json-to-graphql-query';`
in another one.

See #60
