### ISSUE TITLE
Graphql to Json

### ISSUE THREAD

**Issue by TarantoHestis** [dupski/json-to-graphql-query#8]
I'm thinking there should be a Graphql to Json function in this library. 

Use case would be to alter existing graphql queries dynamically.

**Comment by dupski** [comment]
This would take quite a lot of development effort and maintenance to support every permutation of GraphQL queries, and not something I would consider taking on at the moment.

You can use the "gql" template tag to get a full AST for your queries: https://www.npmjs.com/package/graphql-tag
It probably wouldn't be too hard from there to convert back to our JSON format, but I feel that is beyond the scope of this library.

The "graphql-to-json-query" package name is available on npm if you fancy it ;)
